language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install sphinx
  - pip install coveralls
  - python setup.py install
# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=bibtexparser setup.py test
  - cd docs
  - make html

after_success:
  - coveralls
